import styles from './outbreak.module.css';
export default function DataAvailability({rcceDocuments=[],datasets,geometry,mines,securityCount,disasterCount,routeData,facilities,onData,onWorkspace,onMines,loading}) {
  const categories=[['sdb','Safe and dignified burial','Compare requests and completed burials.'],['rcce','Community engagement / RCCE','Understand feedback, reach and unanswered concerns.'],['logistics','Logistics and supplies','Identify stock, transport and supply constraints.'],['response','Response presence and capacity','Compare response coverage with areas needing attention.']];
  const entries=[
    {name:'Administrative boundaries',loaded:!!geometry,note:geometry?`${geometry.features.length} areas available.`:'Upload GeoJSON in the main app to map your data.',action:onWorkspace},
    {name:'ACLED / security',loaded:securityCount>0,note:securityCount?`${securityCount} raw records available; dates and locations are validated separately.`:'Upload or enable ACLED in the main app to assess security overlaps.',action:onWorkspace},
    {name:'GDACS disaster alerts',loaded:disasterCount>0,note:disasterCount?`${disasterCount} alerts available; only recent centres inside the uploaded boundaries are included.`:'Refresh disaster data in the main app. Alerts can flag other hazards affecting response planning.',action:onWorkspace},
    {name:'Mining sites',loaded:!!mines,note:mines?`${mines.data.length} documented sites loaded from ${mines.file||'IPIS mining data'}. Historical visits do not confirm current activity.`:'Upload an IPIS workbook or connect the public DRC source. Mining communities can inform surveillance and engagement planning.',action:onData,target:'context',button:'Add mining data'},
    {name:'Origin–destination mobility',loaded:!!routeData,note:routeData?`Observed through ${routeData.end}.`:'Load a connected matrix or upload an origin–destination CSV.',action:onData,target:'context'},
    {name:'Facilities / response locations',loaded:facilities.length>0,note:facilities.length?`${facilities.length} locations available; capacity is not verified.`:'Upload facilities in the main app to show response locations.',action:onWorkspace},
    ...categories.map(([id,name,why])=>{const found=datasets.filter(d=>d.category===id&&d.status==='ready');const reports=id==='rcce'?rcceDocuments.length:0;return {name,loaded:!!found.length||reports>0,note:reports?`${reports} qualitative reports within cut-off; ${found.length} numeric indicators. ${why}`:found.length?`${found.length} indicators loaded. ${why}`:`${why} ${id==='rcce'?'Upload an RCCE document or categorized numeric indicators.':'Upload aggregate data and choose this dataset category.'}`,action:onData,target:id==='rcce'?'reports':'indicators'};})
  ];
  return <section className={styles.panel} aria-label="Data coverage"><h3>Data coverage</h3><p>Missing data limits the assessment. These sources can add useful context; availability does not establish completeness.</p>{datasets.some(d=>d.origin==='upload'&&(!d.category||d.category==='other'))&&<p>Some uploaded indicators are unclassified. Assign their category in the source list to update this checklist.</p>}<div className={styles.coverageGrid}>{entries.map(e=><article key={e.name}><strong>{e.name}</strong><span className={e.loaded?styles.loadedBadge:styles.missingBadge}>{e.loaded?'Loaded':'Not loaded'}</span><p>{e.note}</p>{!e.loaded&&e.action&&<button disabled={loading} onClick={()=>e.action===onData?onData(e.target||'reports'):e.action()}>{e.button||(e.action===onWorkspace?'Open main app':'Add data')}</button>}</article>)}</div></section>;
}
